"""Character catalog tests: creation, ownership, and cross-user visibility.

Character 1 ("Maya", ``OWNER_USER_ID IS NULL``) is seeded by the ``catalog``
fixture and stands in for a built-in character.
"""

from __future__ import annotations

from typing import Any

from httpx import AsyncClient
from sqlalchemy import select

from app.db.models.character import Character
from tests.conftest import auth_user, create_character

BUILTIN_CHARACTER_ID = 1


async def test_create_character(client: AsyncClient, session_factory: Any) -> None:
    headers, user = await auth_user(client, "alice")

    character = await create_character(
        client,
        headers,
        name="Nova",
        description="A calm, curious assistant.",
        avatar_url="https://example.com/nova.png",
        system_prompt="You are Nova, calm and curious.",
    )

    assert isinstance(character["id"], int)  # identity-generated by the database
    assert character["id"] != BUILTIN_CHARACTER_ID
    assert character["name"] == "Nova"
    assert character["description"] == "A calm, curious assistant."
    assert character["avatar_url"] == "https://example.com/nova.png"
    assert character["system_prompt"] == "You are Nova, calm and curious."
    assert character["owner_user_id"] == user["id"]
    assert character["created_at"] is not None

    async with session_factory() as db:
        row = (await db.scalars(select(Character).where(Character.id == character["id"]))).first()
    assert row is not None
    assert row.owner_user_id == user["id"]
    assert row.status == "ACTIVE"
    assert row.created_at is not None
    assert row.updated_at is not None


async def test_create_character_optional_fields_default_to_null(client: AsyncClient) -> None:
    headers, user = await auth_user(client, "alice")

    character = await create_character(client, headers, name="Bare")

    assert character["description"] is None
    assert character["avatar_url"] is None
    assert character["system_prompt"] is None
    assert character["owner_user_id"] == user["id"]


async def test_create_character_owner_comes_from_the_token(
    client: AsyncClient, session_factory: Any
) -> None:
    """The owner is the authenticated user, and immutable columns are never assignable.

    A non-admin who *sends* owner_user_id is rejected outright — see
    ``tests/test_admin.py::test_regular_user_cannot_use_admin_fields``.
    """
    headers_a, _user_a = await auth_user(client, "alice")
    headers_b, user_b = await auth_user(client, "bob")

    response = await client.post(
        "/characters",
        json={"name": "Impostor", "id": 999, "created_at": "1999-01-01T00:00:00Z"},
        headers=headers_b,
    )

    assert response.status_code == 201, response.text
    character = response.json()
    assert character["owner_user_id"] == user_b["id"]
    assert character["id"] != 999
    assert not character["created_at"].startswith("1999")

    async with session_factory() as db:
        row = (await db.scalars(select(Character).where(Character.id == character["id"]))).first()
    assert row is not None
    assert row.owner_user_id == user_b["id"]
    assert row.status == "ACTIVE"

    # Alice does not gain a character she never created.
    response = await client.get("/characters", headers=headers_a)
    assert [c["name"] for c in response.json()] == ["Maya"]


async def test_create_character_requires_authentication(client: AsyncClient) -> None:
    response = await client.post("/characters", json={"name": "Anon"})
    assert response.status_code == 401
    assert response.json() == {"detail": "Not authenticated"}


async def test_create_character_validation(client: AsyncClient) -> None:
    headers, _user = await auth_user(client, "alice")

    invalid_bodies: list[dict[str, Any]] = [
        {},  # name is required
        {"name": ""},  # name must not be blank
        {"name": "x" * 101},  # NAME VARCHAR2(100)
        {"name": "ok", "description": "d" * 501},  # DESCRIPTION VARCHAR2(500)
        {"name": "ok", "avatar_url": "u" * 1001},  # AVATAR_URL VARCHAR2(1000)
        {"name": "ok", "system_prompt": "p" * 9001},  # SYSTEM_PROMPT VARCHAR2(9000)
    ]
    for body in invalid_bodies:
        response = await client.post("/characters", json=body, headers=headers)
        assert response.status_code == 422, (body, response.text)

    # The boundary values themselves are accepted.
    response = await client.post(
        "/characters",
        json={
            "name": "x" * 100,
            "description": "d" * 500,
            "avatar_url": "u" * 1000,
            "system_prompt": "p" * 9000,
        },
        headers=headers,
    )
    assert response.status_code == 201, response.text


async def test_list_characters_hides_other_users_characters(client: AsyncClient) -> None:
    headers_a, user_a = await auth_user(client, "alice")
    headers_b, _user_b = await auth_user(client, "bob")

    await create_character(client, headers_a, name="Alice's Nova")
    await create_character(client, headers_b, name="Bob's Rex")

    response = await client.get("/characters", headers=headers_a)
    assert response.status_code == 200
    characters = response.json()
    # Built-in character + Alice's own, never Bob's.
    assert [c["name"] for c in characters] == ["Maya", "Alice's Nova"]
    assert [c["owner_user_id"] for c in characters] == [None, user_a["id"]]


async def test_get_other_users_character_is_not_found(client: AsyncClient) -> None:
    headers_a, _user_a = await auth_user(client, "alice")
    headers_b, _user_b = await auth_user(client, "bob")

    bob_character = await create_character(client, headers_b, name="Bob's Rex")

    response = await client.get(f"/characters/{bob_character['id']}", headers=headers_a)
    assert response.status_code == 404
    assert response.json() == {"detail": "Character not found"}

    # Bob still sees his own, and both users see the built-in one.
    response = await client.get(f"/characters/{bob_character['id']}", headers=headers_b)
    assert response.status_code == 200
    for headers in (headers_a, headers_b):
        response = await client.get(f"/characters/{BUILTIN_CHARACTER_ID}", headers=headers)
        assert response.status_code == 200


async def test_conversation_with_another_users_character_is_rejected(client: AsyncClient) -> None:
    headers_a, _user_a = await auth_user(client, "alice")
    headers_b, _user_b = await auth_user(client, "bob")

    bob_character = await create_character(client, headers_b, name="Bob's Rex")

    response = await client.post(
        "/conversations", json={"character_id": bob_character["id"]}, headers=headers_a
    )
    assert response.status_code == 404
    assert response.json() == {"detail": "Character not found"}

    # Bob can start a conversation with his own character.
    response = await client.post(
        "/conversations", json={"character_id": bob_character["id"]}, headers=headers_b
    )
    assert response.status_code == 201, response.text
    assert response.json()["character"]["id"] == bob_character["id"]
